spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.application.name=FitnessCenterAdmin
server.port=8081
admin.file.path=C:/Users/L O Q/Desktop/SLIIT/Y1S2/OOP/Project/FitnessCenterAdmin/data/admins.txt
member.file.path=C:/Users/L O Q/Desktop/SLIIT/Y1S2/OOP/Project/FitnessCenterAdmin/data/members.txt
workout.file.path=C:/Users/L O Q/Desktop/SLIIT/Y1S2/OOP/Project/FitnessCenterAdmin/data/workouts.txt
payment.file.path=C:/Users/L O Q/Desktop/SLIIT/Y1S2/OOP/Project/FitnessCenterAdmin/data/payments.txt
renewal.file.path=C:/Users/L O Q/Desktop/SLIIT/Y1S2/OOP/Project/FitnessCenterAdmin/data/renewals.txt
diet.file.path=C:/Users/L O Q/Desktop/SLIIT/Y1S2/OOP/Project/FitnessCenterAdmin/data/diets.txt